language: generic
sudo: required

services:
  - docker

before_install:
  - docker -t artemalieinikov/frontend-react-app -f ./frontend-react-app/Dockerfile.dev ./frontend-react-app

script:
  - docker run -e CI=true artemalieinikov/frontend-react-app npm run test